### ISSUE TITLE
$nats::service_provider param in the service.pp causes rspec error

### ISSUE THREAD

**Issue by dhollinger** [choria-io/puppet-nats#20]
I've noticed when trying to write tests that validate compilation of a module, I consistently get the following error:

`Evaluation Error: Unknown variable: 'nats::service_provider'`

What does this variable do as it's not referenced or set anywhere else in the module. Despite the RSpec issues, the module appears to be functioning as expected on my master.

Should the service resource's `provider` value be set to the value of `nats::service_type` rather than `nats::service_provider`?

Proposed solution:
``` puppet
class nats::service {
  service { $nats::service_name:
    ensure   => $nats::service_ensure,
    enable   => true,
    provider => $nats::service_type,
  }
}
```

Before I submit a PR, I want to validate that there isn't something I'm missing in the module. Otherwise, I'll update, test, and create a PR

**Comment by ripienaar** [comment]
yeh this looks like its a bug for sure.  Your PR seems good but the tests are failing - perhaps now the right code paths are run we're hitting some missing dependencies?

**Comment by dhollinger** [comment]
Just looked at those tests again. Since you're pulling from the latest commit from puppet-collectd's github repo, there is a new dependency that the `.fixtures.yml` isn't pulling. The latest (unreleased) codebase for [voxpupuli/puppet-collectd](https://github.com/voxpupuli/puppet-collectd.git) now requires [stahnma/puppet-module-epel](https://github.com/stahnma/puppet-module-epel) as a dependency

**Comment by dhollinger** [comment]
Added https://github.com/choria-io/puppet-nats/pull/21/commits/2e0a684d3a3bb3b624eb1582929d3e9c6f35a7d2 to the Pull Request
