### ISSUE TITLE
cert_file and key_file should default to using ${certname}.pem

### ISSUE THREAD

**Issue by adastidar** [choria-io/puppet-nats#23]
The [default](https://github.com/choria-io/puppet-nats/blob/master/manifests/init.pp#L20-L21) locations for certs can instead be: 

```puppet
  String $cert_file = "/etc/puppetlabs/puppet/ssl/certs/${clientcert}.pem",
  String $key_file = "/etc/puppetlabs/puppet/ssl/private_keys/${clientcert}.pem",
```

Right now, I need to override the two params on my master.

**Comment by ripienaar** [comment]
@adastidar better to use `$trusted["certname"]` but I agree, do you want to make a PR?
