### ISSUE TITLE
sysvinit is not a valid service provider on CentOS6

### ISSUE THREAD

**Issue by adastidar** [choria-io/puppet-nats#25]
Couple of issues on CentOS 6 master.

- [x] Default  provider on CentOS/RHEL 6 variants is `redhat`
- [x] sysvinit is not a valid provider based on puppet [docs](https://docs.puppet.com/puppet/latest/types/service.html#service-providers). Need to default this to `init` instead.

**Comment by ripienaar** [comment]
thanks @adastidar
