### ISSUE TITLE
Packaging and the Go binary blob

### ISSUE THREAD

**Issue by jeefberkey** [choria-io/puppet-nats#34]
I've been following an issue, https://github.com/nats-io/gnatsd/issues/404, from the NATS team regarding proper packaging for NATS. 

As it stands, there is an unsigned binary blob in this module that can't easily be put on customer systems.

Once that issue is resolved and there are packages available, can we assume the use of the vendored and signed packages and remove the binary blob?

**Comment by ripienaar** [comment]
I would support a flag to enable the package yes.

**Comment by smortex** [comment]
I am preparing a PR to add the possibility to install gnatsd using packages (because I use a FreeBSD server where a Linux binary is not what I want, and we have packages for this).

I plan to add the following configurable parameters:

```yaml
nats::manage_package: false
nats::package_name: gnatsd
nats::package_ensure: present
```

I guess that adding support for Linux distro would then just consist in adding the relevant repository?

**Comment by ripienaar** [comment]
soonish the use of gnatsd will go away, there's a new `choria` daemon coming that combines this, federation and mcollectived all in one.

This looks good though

**Comment by smortex** [comment]
@ripienaar I use this along with a few more changes to support FreeBSD.  Do you mind if I open PRs so that I can track the official repo?

**Comment by ripienaar** [comment]
yeah go on this is fine for now as long as its off by default

**Comment by ripienaar** [comment]
@jeefberkey @smortex if either of you are interested I am nearing a point where we can test RHEL packages for a new middleware broker and federation broker that comes in one binary and packaged as a RPM

**Comment by ripienaar** [comment]
@smortex yes, though do not package yet, right now looking for testers of the functionality rather than quite ready to have it packaged and quite a way from shipping ready :)

**Comment by smortex** [comment]
@ripienaar ACK.  I will not push the port to FreeBSD for now!  Let's try to compile this!

**Comment by ripienaar** [comment]
@smortex ok :) the README has details on how to set it up to replace your NATS

**Comment by jeefberkey** [comment]
@ripienaar I can write a test in simp/simp_choria when you're ready :)

**Comment by ripienaar** [comment]
@jeefberkey So the repo in question is https://github.com/choria-io/go-choria there are RPMs for el6/7 (64bit only) and SRPMs in the yum repo https://dl.bintray.com/choria/el-yum/

```
[choria]
name=Choria Orchestrator - $architecture
baseurl=https://dl.bintray.com/choria/el-yum/el$releasever/$basearch
gpgcheck=0
repo_gpgcheck=0
enabled=1
protect=1
```

I'll start signing them in due course

The RPM includes sample configs and the README of the repo tells you a bit. 

My broker config on all my machines have:

```ini
# /etc/choria/broker.conf
logfile = /var/log/choria.log
loglevel = info

plugin.choria.broker_network = true
plugin.choria.network.peers = nats://c1.example.net:5222, nats://c2.example.net:5222, nats://c3.example.net:5222

plugin.choria.broker_federation = true
plugin.choria.federation.cluster = development
plugin.choria.federation.instance = c1.example.net
plugin.choria.srv_domain = dev.example.net

plugin.choria.stats_port = 8222
plugin.choria.stats_address = 0.0.0.0
```

This is for the `choria-broker` service

Like choria, this all assumes you have puppet agent going and certs exist - it will use all the same certs and stuff as the mco one.

**Comment by ripienaar** [comment]
ping @bje

**Comment by ripienaar** [comment]
Just to frame this, this is early days and I do make quite a few changes to this still, so please do not spend much time packaging and all that, looking for early feedback :) I have this running stable for 2 weeks now with 1k nodes connected, no memory leaks or anything weird so it's already pretty solid.

**Comment by ripienaar** [comment]
ping @bastelfreak

**Comment by ripienaar** [comment]
deprecated in https://github.com/choria-io/puppet-nats/pull/72
