### ISSUE TITLE
Module fails when system is not configured

### ISSUE THREAD

**Issue by houtmanj** [choria-io/puppet-nats#38]
The logic leads to a fail() when the current system is not included in the list of servers. 
I understand this, but is there away to do this that does not fail the whole puppet run?

Our provision/installation is highly automated, but things get difficult when the first puppet run fails and is not able to setup the basic essentials of a system.

I would prefer to replace the fail() with a prominent message for the client.

**Comment by ripienaar** [comment]
only option would be a notify I guess, that's probably ok yeah.  Do you want to do a PR to that effect?

**Comment by houtmanj** [comment]
Sure, Would you want the behavior to be selectable?

something like: 

$fail_on_missing_config = true

**Comment by ripienaar** [comment]
nah I think notify is fine here https://github.com/choria-io/puppet-nats/blob/master/manifests/init.pp#L46 the other one should stay as is

**Comment by ripienaar** [comment]
Thank you @houtmanj
