### ISSUE TITLE
FreeBSD support

### ISSUE THREAD

**Issue by smortex** [choria-io/puppet-nats#50]
- [x] Drop AIO checks;
- [x] Allow installation through packages;
- [x] Add support for the `bsd` service provider;
- [x] Use proper default paths on FreeBSD;
- [x] Add tests.

Original issue was to drop AIO checks only

-------

The module currently requires an AIO host:

https://github.com/choria-io/puppet-nats/blob/02659bb73885fdf1763ab76caeac42da01475b51/manifests/init.pp#L35-L37

However, it does not seems to have strong dependencies with the AIO packages: I could successfully use it on FreeBSD.

**Comment by ripienaar** [comment]
I am still fairly sure I can, given the time I have and the resources available, only support AIO users.

I know its not technically that choria requires AIO to function, but I require AIO to be used to function as a community leader and primarily support giver.

This is the motivation for this.

**Comment by smortex** [comment]
:thinking: how can we make sure users won't annoy you…  Adding some undocumented parameter?
